{
 "title": "Finance Dash (USD)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Circulating ggAVAX Value",
   "type": "stat",
   "description": "Total circulating ggAVAX value in USD\n\nformula: circulating ggAVAX * AVAX price in USD\n\nfunction: TokenggAVAX.totalAssets() ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(total_assets / ggavax_avax_exchange_rate) * avax_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Liquid Staker AVAX Validating",
   "type": "stat",
   "description": "The amount of liquid staking funds staked on a minipool and validating on chain, is USD.\n\nformula: stakingTotalAssets * AVAX price in USD\n\nFunction: ggAVAX.stakingTotalAssets()",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_avax_liq_staker_amt * avax_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GGP Staked",
   "type": "stat",
   "description": "Total GGP staked in the protocol\n\nfunction: staking.getTotalGGPStake()",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_ggp_stake * avax_price * ggp_price_in_avax",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount Available For Staking",
   "type": "stat",
   "description": "AVAX ready to be staked on minipools, in USD.\n\nformula: amountAvailableForStaking * AVAX price in USD\n\nfunction: ggAVAX.amountAvailableForStaking()",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amount_available_for_staking * avax_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Rewards Value for ggAVAX",
   "type": "stat",
   "description": "The amount of rewards distributed in the most recent cycle, in USD.\n\nformula: lastRewardsAmt * AVAX price in USD\n\nfunction: ggAVAX.lastRewardsAmt variable",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_rewards_amt / ggavax_avax_exchange_rate) * avax_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last GGP<->AVAX Update Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ggp_price_update_time * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GGP <-> USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ggp_price_in_avax * avax_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GGP <-> AVAX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "AVAX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ggp_price_in_avax", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVAX <-> USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avax_price", "legendFormat": "__auto" }
   ]
  },
  { "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 } }
 ]
}