{
 "title": "GoGoPool Protocol",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 19, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://app.gogopool.com\" class=\"btn btn--main-cta\">Go to Gogopool</a>\n\n<h2>Token Contracts</h2>\n\n<ul>\n  <li>\n    <a target=\"_blank\" href=\"https://snowtrace.io/token/0x69260B9483F9871ca57f81A90D91E2F96c2Cd11d\">GGP</a>\n  </li>\n  <li>\n    <a target=\"_blank\" href=\"https://snowtrace.io/token/0xa25eaf2906fa1a3a13edac9b9657108af7b703e3\">ggAVAX</a>\n  </li>\n</ul>\n\n\n<h2>Links</h2>\n<ul>\n  <li>\n<a target=\"_blank\" href=\"https://panopticon.fly.dev/home\">Panopticon</a>\n</li>\n  <li>\n<a target=\"_blank\" href=\"https://dexscreener.com/avalanche/0xae671e0bf91ceaa4a6cb0d1294735ea3236d4586\">DexScreener</a>\n </li>\n <li>\n <a target=\"_blank\" href=\"https://www.coingecko.com/en/coins/gogopool\">CoinGecko</a>\n </li>\n</ul>\n"
   }
  },
  {
   "title": "Protocol TVL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((total_assets + ignoring(status) (minipools_status_staking * 1000)) * avax_price) + (total_ggp_stake * ggp_price_in_avax * avax_price)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liquid Staking APR",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "options": {
    "content": "<h1 class=\"apr\">5.79%</h1>  "
   }
  },
  {
   "title": "NodeOp APR",
   "type": "text",
   "description": "APR is calculated as a combination of AVAX staking  rewards plus GGP staking rewards paid out monthly. GGP rewards are a fixed amount each month that is split pro-rata between all eligible GGP stakers.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<h1 class=\"apr\">375% -- 2,500%</h1>"
   }
  },
  {
   "title": "Available Minipools",
   "type": "stat",
   "description": "amount_available_for_staking\n\nfunction: TokenggAVAX.amountAvailableForStaking() ",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(amount_available_for_staking / 1000) - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Minipools",
   "type": "stat",
   "description": "Total minipools with status = staking",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minipools_status_staking    ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GGP Staked",
   "type": "stat",
   "description": "Total GGP staked in the protocol\n\nfunction: staking.getTotalGGPStake()",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_ggp_stake{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GGP Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ggp_price_in_avax * avax_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reward Cycle Start",
   "type": "stat",
   "description": "In your local timezone",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(rewards_cycle_seconds) * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rewards Eligibility",
   "type": "stat",
   "description": "At least one of your minipool's must have been started before this time in order to be eligible for this GGP rewards cycle.",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rewards_cycle_seconds + 2592000 - rewards_eligibility_min_seconds) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reward Cycle End",
   "type": "stat",
   "description": "In your local timezone",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rewards_cycle_seconds + 2592000) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minipools",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minipools_status_cancelled)",
     "legendFormat": "Cancelled"
    },
    { "expr": "sum(minipools_status_error)", "legendFormat": "Errors" },
    { "expr": "sum(minipools_status_finished)", "legendFormat": "Finished" },
    {
     "expr": "sum(minipools_status_withdrawable)",
     "legendFormat": "Widthdrawable"
    },
    { "expr": "sum(minipools_status_launched)", "legendFormat": "Launched" },
    {
     "expr": "sum(minipools_status_prelaunch)",
     "legendFormat": "PreLaunch"
    },
    { "expr": "sum(minipools_status_staking)", "legendFormat": "Staking" }
   ]
  },
  {
   "title": "Protocol Parameters",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 19 },
   "targets": [
    { "expr": "total_avax_liq_staker_amt", "legendFormat": "__auto" },
    { "expr": "total_assets", "legendFormat": "__auto" },
    { "expr": "last_sync", "legendFormat": "__auto" },
    { "expr": "last_rewards_amt", "legendFormat": "__auto" },
    { "expr": "total_released_assets", "legendFormat": "__auto" },
    { "expr": "staking_total_assets", "legendFormat": "__auto" },
    { "expr": "amount_available_for_staking", "legendFormat": "__auto" },
    { "expr": "staker_count", "legendFormat": "__auto" },
    { "expr": "total_ggp_stake", "legendFormat": "__auto" },
    {
     "expr": "rewards_eligibility_min_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "rewards_cycle_seconds", "legendFormat": "__auto" },
    { "expr": "inflation_interval_rate", "legendFormat": "__auto" },
    { "expr": "inflation_interval_seconds", "legendFormat": "__auto" },
    { "expr": "minipool_min_avax_staking_amt", "legendFormat": "__auto" },
    {
     "expr": "minipool_node_commission_fee_pct",
     "legendFormat": "__auto"
    },
    { "expr": "minipool_max_avax_assignment", "legendFormat": "__auto" },
    { "expr": "minipool_min_avax_assignment", "legendFormat": "__auto" },
    { "expr": "expected_avax_rewards_rate", "legendFormat": "__auto" },
    { "expr": "max_collateralization_ratio", "legendFormat": "__auto" },
    { "expr": "min_collateralization_ratio", "legendFormat": "__auto" },
    { "expr": "target_ggavax_reserve_rate", "legendFormat": "__auto" },
    { "expr": "ggp_price_in_avax", "legendFormat": "__auto" },
    { "expr": "ggp_price_update_time", "legendFormat": "__auto" },
    { "expr": "can_start_rewards_cycle", "legendFormat": "__auto" },
    { "expr": "reward_cycle_elapsed", "legendFormat": "__auto" },
    { "expr": "reward_cycle_total_amt", "legendFormat": "__auto" },
    { "expr": "inflation_interval_start_time", "legendFormat": "__auto" },
    { "expr": "inflation_intervals_elapsed", "legendFormat": "__auto" },
    { "expr": "inflation_amt", "legendFormat": "__auto" },
    {
     "expr": "claiming_contract_distribution_node_op",
     "legendFormat": "__auto"
    },
    {
     "expr": "claiming_contract_distribution_protocol_dao",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ggAVAX Last Rewards",
   "type": "stat",
   "description": "The amount of rewards distributed in a the most recent cycle\n\nfunction: ggAVAX.lastRewardsAmt variable",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ggAVAX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_rewards_amt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Sync Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_sync * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last GGP<->AVAX Update Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ggp_price_update_time * 1000", "legendFormat": "__auto" }
   ]
  },
  { "gridPos": { "h": 6, "w": 5, "x": 19, "y": 23 } }
 ]
}