name: metrics
version: "3.9"

services:
  harvester:
    container_name: harvester
    image: ghcr.io/multisig-labs/ceres:main
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./ceres/harvester:/app/config
    command: serve
    stop_signal: SIGINT
    user: "0:0"
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 30s

  exporter:
    container_name: exporter
    restart: always
    platform: linux/amd64
    volumes:
      - ./ceres/exporter:/app/config
    image: quay.io/prometheuscommunity/json-exporter
    command:
      - --config.file=/app/config/exporter.yml
    ports:
      - "7979:7979"
    user: "${UID:-0}:${GID:-0}"

  prometheus:
    container_name: prometheus
    platform: linux/amd64
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./ceres/prometheus:/etc/prometheus
      - ./ceres_data/prometheus:/prometheus
    user: "${UID:-0}:${GID:-0}"

  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./ceres/caddy:/etc/caddy
      - ./ceres_data/caddy:/data
