FROM lukechannings/deno:v1.36.2 AS builder

WORKDIR /app

COPY . .

RUN deno compile --allow-sys --allow-env --unstable --unsafely-ignore-certificate-errors --allow-net --allow-write --allow-read --output ceres main.ts

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/ceres .
COPY --from=builder /app/tokenholders.csv .

ENTRYPOINT ["/app/ceres", "--mode"]
