FROM denoland/deno:1.34.1 AS builder

WORKDIR /app

COPY . .

RUN deno compile --unstable --allow-env --allow-sys --unsafely-ignore-certificate-errors --allow-net --allow-write --allow-read --output ceres main.ts

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/ceres .
COPY --from=builder /app/tokenholders.csv .

ENTRYPOINT ["/app/ceres", "--mode"]
