FROM lukechannings/deno:v1.28.3 AS builder

WORKDIR /app

COPY . .

RUN deno compile --allow-net --allow-write --allow-read --output ceres main.ts

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/ceres .

ENTRYPOINT ["/app/ceres"]

